### ISSUE TITLE
Add repository metadata

### ISSUE THREAD

**Issue by bedroge** [EESSI/filesystem-layer#81]
Related to #67, but it may also be useful to add some custom metadata, e.g. the latest version of the repo (requested by @ocaisa).

**Comment by bedroge** [comment]
This should be added to our Stratum 0 playbook.

**Comment by bedroge** [comment]
The only tricky thing is that this playbook would need to run regularly in order to keep the `latest` entry up to date. Or, perhaps we could use a hook that will update this information whenever the symlink is changed:
https://cvmfs.readthedocs.io/en/stable/cpt-repo.html#customizable-actions-using-server-hooks

**Comment by rptaylor** [comment]
Also keep in mind this is something you would probably want to synchronize across all nodes, and it is not possible to do an atomic  update across all nodes in a cluster in a completely synchronized way, with psh or otherwise. There would always be some nodes that get changed sooner than others.  So I think it would be better to handle this at the user application level.
